### ISSUE TITLE
Install instructions needed

### ISSUE THREAD

**Issue by ldormoy** [Graylog2/graylog-plugin-filter-ipanonymizer#1]
Hi,

How can I install this plugin on Graylog2 0.90.0 ?

I tried to package with Maven, copy the jar in the plugins directory and restart graylog2-server.

Is there something else to do ?

Thanks for you help !

**Comment by edmundoa** [comment]
Hi,

We are really sorry that we didn't get back to you earlier 😿 

Assuming in this long time you updated to Graylog 1.3 or 2.0, all you need to do is to download the compiled jar file from the [releases page](https://github.com/Graylog2/graylog-plugin-ipanonymizer/releases), put it into your plugins directory, and restart Graylog server.

As this issue is really old, and probably not an issue any more, I'm closing the ticket. Please let us know if you still have problems installing the plugin.

Thank you!
